# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x16muleradar.ingestion.v1\"\xd7\x01\n\x10TransactionEvent\x12\r\n\x05tx_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_account\x18\x02 \x01(\t\x12\x12\n\nto_account\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x06 \x01(\t\x12\x16\n\x0epayment_format\x18\x07 \x01(\t\x12\x14\n\x0ctx_timestamp\x18\x08 \x01(\t\x12\x11\n\tdevice_id\x18\t \x01(\t\x12\x16\n\x0einstitution_id\x18\n \x01(\t\";\n\tIngestAck\x12\r\n\x05tx_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"U\n\rIngestSummary\x12\x10\n\x08received\x18\x01 \x01(\x03\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x03\x12\x10\n\x08rejected\x18\x03 \x01(\x03\x12\x0e\n\x06\x65rrors\x18\x04 \x03(\t\"\x0f\n\rHealthRequest\"Y\n\x0eHealthResponse\x12\x0f\n\x07serving\x18\x01 \x01(\x08\x12\x10\n\x08kafka_ok\x18\x02 \x01(\x08\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x13\n\x0bkafka_topic\x18\x04 \x01(\t2\xa7\x03\n\x10IngestionService\x12^\n\x0fSendTransaction\x12(.muleradar.ingestion.v1.TransactionEvent\x1a!.muleradar.ingestion.v1.IngestAck\x12g\n\x12StreamTransactions\x12(.muleradar.ingestion.v1.TransactionEvent\x1a%.muleradar.ingestion.v1.IngestSummary(\x01\x12l\n\x19StreamTransactionsWithAck\x12(.muleradar.ingestion.v1.TransactionEvent\x1a!.muleradar.ingestion.v1.IngestAck(\x01\x30\x01\x12\\\n\x0bHealthCheck\x12%.muleradar.ingestion.v1.HealthRequest\x1a&.muleradar.ingestion.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONEVENT']._serialized_start=46
  _globals['_TRANSACTIONEVENT']._serialized_end=261
  _globals['_INGESTACK']._serialized_start=263
  _globals['_INGESTACK']._serialized_end=322
  _globals['_INGESTSUMMARY']._serialized_start=324
  _globals['_INGESTSUMMARY']._serialized_end=409
  _globals['_HEALTHREQUEST']._serialized_start=411
  _globals['_HEALTHREQUEST']._serialized_end=426
  _globals['_HEALTHRESPONSE']._serialized_start=428
  _globals['_HEALTHRESPONSE']._serialized_end=517
  _globals['_INGESTIONSERVICE']._serialized_start=520
  _globals['_INGESTIONSERVICE']._serialized_end=943
# @@protoc_insertion_point(module_scope)
