# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import transaction_pb2 as transaction__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in transaction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTransaction = channel.unary_unary(
                '/muleradar.ingestion.v1.IngestionService/SendTransaction',
                request_serializer=transaction__pb2.TransactionEvent.SerializeToString,
                response_deserializer=transaction__pb2.IngestAck.FromString,
                _registered_method=True)
        self.StreamTransactions = channel.stream_unary(
                '/muleradar.ingestion.v1.IngestionService/StreamTransactions',
                request_serializer=transaction__pb2.TransactionEvent.SerializeToString,
                response_deserializer=transaction__pb2.IngestSummary.FromString,
                _registered_method=True)
        self.StreamTransactionsWithAck = channel.stream_stream(
                '/muleradar.ingestion.v1.IngestionService/StreamTransactionsWithAck',
                request_serializer=transaction__pb2.TransactionEvent.SerializeToString,
                response_deserializer=transaction__pb2.IngestAck.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/muleradar.ingestion.v1.IngestionService/HealthCheck',
                request_serializer=transaction__pb2.HealthRequest.SerializeToString,
                response_deserializer=transaction__pb2.HealthResponse.FromString,
                _registered_method=True)


class IngestionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendTransaction(self, request, context):
        """Satuan — cocok utk transaksi bernilai tinggi yg butuh konfirmasi segera.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTransactions(self, request_iterator, context):
        """Client-streaming — bank membanjirkan transaksi, dapat 1 ringkasan di akhir.
        Paling efisien utk throughput tinggi (tak ada balasan per-item).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTransactionsWithAck(self, request_iterator, context):
        """Bidirectional — balasan per-transaksi sambil stream berjalan. Dipakai
        kalau bank butuh tahu status tiap transaksi tanpa menunggu batch selesai.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Kesehatan gateway + koneksi Kafka di belakangnya.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTransaction,
                    request_deserializer=transaction__pb2.TransactionEvent.FromString,
                    response_serializer=transaction__pb2.IngestAck.SerializeToString,
            ),
            'StreamTransactions': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTransactions,
                    request_deserializer=transaction__pb2.TransactionEvent.FromString,
                    response_serializer=transaction__pb2.IngestSummary.SerializeToString,
            ),
            'StreamTransactionsWithAck': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTransactionsWithAck,
                    request_deserializer=transaction__pb2.TransactionEvent.FromString,
                    response_serializer=transaction__pb2.IngestAck.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=transaction__pb2.HealthRequest.FromString,
                    response_serializer=transaction__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'muleradar.ingestion.v1.IngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('muleradar.ingestion.v1.IngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/muleradar.ingestion.v1.IngestionService/SendTransaction',
            transaction__pb2.TransactionEvent.SerializeToString,
            transaction__pb2.IngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTransactions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/muleradar.ingestion.v1.IngestionService/StreamTransactions',
            transaction__pb2.TransactionEvent.SerializeToString,
            transaction__pb2.IngestSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTransactionsWithAck(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/muleradar.ingestion.v1.IngestionService/StreamTransactionsWithAck',
            transaction__pb2.TransactionEvent.SerializeToString,
            transaction__pb2.IngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/muleradar.ingestion.v1.IngestionService/HealthCheck',
            transaction__pb2.HealthRequest.SerializeToString,
            transaction__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
